inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  AllowSymlinksInCacheRootDirectory: true
  SuggestExtensions:
    rubocop-rake: false

Metrics/AbcSize:
  Max: 16
  Exclude:
   - 'test/**/*'

Layout/LineLength:
  Max: 140
  Exclude:
   - 'test/**/*'

Lint/FloatComparison:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 32
  Exclude:
   - 'test/**/*'

Metrics/ClassLength:
  Exclude:
   - 'test/**/*'

Style/MultilineIfModifier:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
